set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,chinese,cp936
set clipboard=unnamedplus
set scrolloff=8
set sidescrolloff=8
set number
set relativenumber 
set cursorline 
set tabstop=2 
set softtabstop=2 
set shiftround 
set ignorecase 
set smartcase 
set cmdheight=1 
set autoread 
set mouse=a
